// ============================================================================
// User Authentication Types
// ============================================================================

// Note: User type is generated by Prisma from the model in schema.prisma

export interface SystemStatus {
  initialized: boolean
  allowSignups: boolean
}

export interface Setting {
  key: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  value: any
  updatedAt: Date
  updatedBy: string | null
}

export interface LoginResponse {
  authUrl: string
  state: string
}

// ============================================================================
// Storage Provider Types
// ============================================================================

export interface StorageProviderConfig {
  provider: 'google_drive_shared' | 'google_drive_my_drive' | 'google_cloud_storage' | 's3' | 'cloudflare_r2' | 'digitalocean_spaces'
  name: string
  icon: string
  authType: 'oauth' | 'api_key' | 'service_account'
  features: {
    supportsSharedDrives?: boolean
    supportsVersioning?: boolean
    maxFileSize?: number // in bytes
    allowedFileTypes?: string[] // MIME types
  }
}

// Storage adapter interface (for implementing different providers)
export interface IStorageAdapter {
  provider: string

  // Initialize the adapter with credentials
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  initialize(credentials: any): Promise<void>

  // List available destinations (drives, buckets, etc.)
  listDestinations(): Promise<StorageDestinationInfo[]>

  // List folders within a destination
  listFolders(destinationId: string, parentPath?: string): Promise<StorageFolder[]>

  // Upload a file (stream-based)
  uploadFile(params: UploadFileParams): Promise<UploadFileResult>

  // Create a folder
  createFolder(destinationId: string, name: string, parentPath?: string): Promise<StorageFolder>

  // Rename a folder
  renameFolder(destinationId: string, folderPath: string, newName: string): Promise<void>

  // Delete a folder (for retention cleanup)
  deleteFolder(destinationId: string, folderPath: string): Promise<void>

  // List backups (versioned folders)
  listBackups(destinationId: string, basePath: string): Promise<BackupVersion[]>

  // Validate credentials
  validateCredentials(): Promise<boolean>
}

// Note: StorageDestination type is generated by Prisma from the model in schema.prisma
// This is a simplified version for the storage adapter interface
export interface StorageDestinationInfo {
  id: string
  name: string
  provider: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  metadata?: Record<string, any>
}

export interface StorageFolder {
  id: string
  name: string
  path: string
  parentId?: string
  createdTime?: Date
  modifiedTime?: Date
}

export interface UploadFileParams {
  destinationId: string
  folderPath: string
  fileName: string
  fileStream: NodeJS.ReadableStream
  fileSize: number
  mimeType: string
  onProgress?: (progress: UploadProgress) => void
}

export interface UploadFileResult {
  fileId: string
  fileName: string
  size: number
  path: string
}

export interface UploadProgress {
  bytesUploaded: number
  totalBytes: number
  percentage: number
}

export interface BackupVersion {
  name: string
  path: string
  createdTime: Date
  size?: number
  fileCount?: number
}

// NAS filesystem types
export interface NASFileInfo {
  name: string
  path: string
  type: 'file' | 'directory' | 'symlink'
  size?: number
  modified?: Date
  permissions?: string
}

export interface NASDirectoryInfo {
  path: string
  items: NASFileInfo[]
  totalSize?: number
  fileCount?: number
  directoryCount?: number
}

// Backup job execution types
export interface BackupJobExecution {
  jobId: string
  historyId: string
  sourcePath: string
  destinationId: string
  credentialId: string
  namePattern: string
  retentionPolicy: {
    type: 'VERSION_COUNT' | 'DAYS' | 'HYBRID'
    count?: number
    days?: number
  }
}

export interface BackupExecutionResult {
  success: boolean
  historyId: string
  filesScanned: number
  filesUploaded: number
  filesFailed: number
  bytesUploaded: number
  duration: number // milliseconds
  remotePath: string
  error?: string
}

// Encryption utilities types (EncryptedData is exported from crypto.ts)
export interface DecryptedCredentials {
  provider: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  data: any
  expiresAt?: Date
}

// WebSocket event types
export type WebSocketEventType =
  | 'backup:progress'
  | 'backup:status'
  | 'backup:complete'
  | 'backup:error'
  | 'queue:stats'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface WebSocketEvent<T = any> {
  type: WebSocketEventType
  payload: T
  timestamp: number
}

// Queue job types
export interface BackupJobData {
  jobId: string
  historyId: string
  executionParams: BackupJobExecution
}

export interface BackupJobProgress {
  historyId: string
  status: string
  filesScanned: number
  filesUploaded: number
  filesFailed: number
  bytesUploaded: number
  currentFile?: string
  estimatedTimeRemaining?: number
  uploadSpeed?: number
}

// API types
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface APISuccessResponse<T = any> {
  success: true
  data?: T
  message?: string
}

export interface APIErrorResponse {
  success: false
  error: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  details?: any
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type APIResponse<T = any> = APISuccessResponse<T> | APIErrorResponse

export interface PaginatedResponse<T> {
  success: true
  data: T[]
  pagination: {
    total: number
    limit: number
    offset: number
    hasMore: boolean
  }
}
